version: '2'
services:
  mysql2:
    build: containers/mysql
    #image: mysql
#    volumes:
#      - mysql:/var/lib/mysql
#      - .mysql/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld2.conf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=mitpassword

    networks:
      - db

  web:
    build: .
    volumes:
      - .:/app
      - /app/log
    depends_on:
      - mysql2
    networks:
      - db

  nginx:
    build: containers/nginx
    ports:
      - "8080:80"
    # Put logs in app/log
    volumes_from:
      - web
    depends_on:
      - web

  
networks:
  db:
volumes:
  mysql:
