default: &default
  adapter: mysql2
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_URL'] %>
  username: root
  password: rootpassword
  host: mysql2
  port: 3306

development:
  <<: *default
  database: flyover_development

test:
  <<: *default
  database: flyover_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
